const actionTypes = {
  SHOW_TAG_INFO_WIDGET: 'SHOW_TAG_INFO_WIDGET',
  HIDE_TAG_INFO_WIDGET: 'HIDE_TAG_INFO_WIDGET',
  SHOW_AUTHOR_INFO_WIDGET: 'SHOW_AUTHOR_INFO_WIDGET',
  HIDE_AUTHOR_INFO_WIDGET: 'HIDE_AUTHOR_INFO_WIDGET',
  SHOW_REF_WIDGET: 'SHOW_REF_WIDGET',
  HIDE_REF_WIDGET: 'HIDE_REF_WIDGET',
  SHOW_SUBSCRIBE_WIDGET: 'SHOW_SUBSCRIBE_WIDGET',
  HIDE_SUBSCRIBE_WIDGET: 'HIDE_SUBSCRIBE_WIDGET'
};
export default actionTypes;
