export const widgetActions = {
  SHOW_TAG_INFO_WIDGET: 'SHOW_TAG_INFO_WIDGET',
  HIDE_TAG_INFO_WIDGET: 'HIDE_TAG_INFO_WIDGET',
  SHOW_AUTHOR_INFO_WIDGET: 'SHOW_AUTHOR_INFO_WIDGET',
  HIDE_AUTHOR_INFO_WIDGET: 'HIDE_AUTHOR_INFO_WIDGET',
  SHOW_REF_WIDGET: 'SHOW_REF_WIDGET',
  HIDE_REF_WIDGET: 'HIDE_REF_WIDGET',
  SHOW_SUBSCRIBE_WIDGET: 'SHOW_SUBSCRIBE_WIDGET',
  HIDE_SUBSCRIBE_WIDGET: 'HIDE_SUBSCRIBE_WIDGET',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE'
};
export const userActions = {
  LOAD_PROFILE: 'LOAD_PROFILE',
  UPDATE_PROFILE: 'UPDATE_PROFILE'
};
export const postActions = {
  LOAD_POSTS: 'LOAD_POSTS',
  LOAD_MORE_POSTS: 'LOAD_MORE_POSTS',
  LOAD_POST: 'LOAD_POST',
  LOAD_DRAFTS: 'LOAD_DRAFTS',
  LOAD_MORE_DRAFTS: 'LOAD_MORE_DRAFTS',
  LOAD_USER_PUBLISHED_POSTS: 'LOAD_USER_PUBLISHED_POSTS',
  LOAD_MORE_USER_PUBLISHED_POSTS: 'LOAD_MORE_USER_PUBLISHED_POSTS'
};
export const questionActions = {
  ADD_QUESTION: 'ADD_QUESTION'
};
export const IMAGE_CTRL = 'IMAGE_EMBED';
export const VIDEO_CTRL = 'VIDEO_EMBED';
export const LINK_CTRL = 'LINK_EMBED';
export const QNA_CTRL = 'QNA_EMBED';
export const CODE_EMBED_CTRL = 'CODE_EMBED';
